# Generated by Django 2.2.12 on 2022-02-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_number', models.CharField(max_length=10)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_ordering.Bank')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_ordering.User')),
            ],
        ),
    ]
